using System;
using System.Collections.Generic;
using System.Text;
using System.Reflection;
using Fuzzware.Schemer.AutoGenerated;
using Fuzzware.Common;
using Fuzzware.Common.DataSchema;
using Fuzzware.Common.XML;

namespace Fuzzware.Schemer.Fuzzers.NumberFuzzing
{
    /// <summary>
    /// This fuzzer will subtract the values provided by the configuration files to the current value of the integer.
    /// Overflows in the subtraction can occur.
    /// </summary>
    class SubtractInteger : AdjustIntegerBase
    {
        public SubtractInteger(ConfigData oConfigData, PreCompData oPreCompData, ObjectDBEntry oSchemaElement)
            : base(oConfigData, oPreCompData, oSchemaElement)
        {
        }

        protected override string GetFuzzerName()
        {
            return GetType().Name;
        }

        protected override void AssignValueFuzzers(IntegerValueFuzzersType FuzzersType)
        {
            if (FuzzersType.SubtractInteger != null)
            {
                Add(GetFuzzerName(), AdjustInteger);
                ConfigDefinedValues = GetValueGroup(FuzzersType.SubtractInteger.ValueGroupRef);
            }
        }

        /// <summary>
        /// Subtracts a value from the configuration array to the passed in Value.  The value from the configuration array
        /// must fit in an Int64.  Overflows can occur in the subtraction.
        /// </summary>
        protected override long OperateOn(int FuzzIndex, long Value)
        {
            Int64 iOperand = 0;
            if (Int64.TryParse(ConfigDefinedValues[FuzzIndex], out iOperand))
            {
                return Value - iOperand;
            }
            // If the configured operand cannot be made to an Int64, then it cannot be subtracted to an Int64.
            throw new SkipStateException();
        }

        /// <summary>
        /// Subtracts a value from the configuration array to the passed in Value.  The value from the configuration array
        /// must be >= Int64.MinValue and &lt;= UInt64.MaxValue.  Overflows can occur in the subtraction.
        /// </summary>
        protected override ulong OperateOn(int FuzzIndex, ulong Value)
        {
            Int64 iOperand = 0;
            if (Int64.TryParse(ConfigDefinedValues[FuzzIndex], out iOperand))
            {
                if (iOperand > 0)
                    return Value - (UInt64)iOperand;
                else
                    return Value + (UInt64)(-1 * iOperand);
            }
            UInt64 uiOperand = 0;
            if (UInt64.TryParse(ConfigDefinedValues[FuzzIndex], out uiOperand))
            {
                return Value - uiOperand;
            }
            throw new SkipStateException();
        }
    }
}
