using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows;
using Fuzzware.Schemas.AutoGenerated;
using Fuzzware.Fuzzsaw.Common.ViewModel;

namespace Fuzzware.Fuzzsaw.Output.ViewModel
{
    public class ExeOutputViewModel : OutputBaseViewModel, IOutputHandler
    {
        #region Dependency Properties

        static readonly DependencyProperty OutputViewModelProperty = DependencyProperty.Register("OutputViewModel", typeof(ExeOutputControlViewModel), typeof(ExeOutputViewModel));
        public ExeOutputControlViewModel OutputViewModel
        {
            get { return (ExeOutputControlViewModel)GetValue(OutputViewModelProperty); }
            set { SetValue(OutputViewModelProperty, value); }
        }

        #endregion

        public ExeOutputViewModel()
        {
            OutputViewModel = new ExeOutputControlViewModel();
        }

        #region IOutputHandler Members

        public Type GetDataOutputHandlerItemType()
        {
            return typeof(Fuzzware.Schemas.AutoGenerated.OutputToExe);
        }

        public EvaluationMethod EvaluationMethod
        {
            get
            {
                if (null == OutputViewModel)
                    OutputViewModel = new ExeOutputControlViewModel();

                m_oEvaluationMethod.Item = OutputViewModel.GetOutputToExe();

                return m_oEvaluationMethod;
            }
            set
            {
                if (!(value.Item is Fuzzware.Schemas.AutoGenerated.OutputToExe))
                    return;

                m_oEvaluationMethod = value;
                OutputViewModel = new ExeOutputControlViewModel((Fuzzware.Schemas.AutoGenerated.OutputToExe)m_oEvaluationMethod.Item);
            }
        }

        #endregion
    }
}
