//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace Fuzzware.Fuzzsaw.FuzzingConfig {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Fuzzware.Fuzzsaw.FuzzingConfig.FuzzDataLibrary")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:Fuzzware.Fuzzsaw.FuzzingConfig.FuzzDataLibrary", IsNullable=false)]
    public partial class FuzzData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool selectedField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Selected {
            get {
                return this.selectedField;
            }
            set {
                this.selectedField = value;
                this.RaisePropertyChanged("Selected");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Fuzzware.Fuzzsaw.FuzzingConfig.FuzzDataLibrary")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:Fuzzware.Fuzzsaw.FuzzingConfig.FuzzDataLibrary", IsNullable=false)]
    public partial class FuzzDataRange : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string startField;
        
        private string endField;
        
        private bool selectedField;
        
        /// <remarks/>
        public string Start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
                this.RaisePropertyChanged("Start");
            }
        }
        
        /// <remarks/>
        public string End {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
                this.RaisePropertyChanged("End");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Selected {
            get {
                return this.selectedField;
            }
            set {
                this.selectedField = value;
                this.RaisePropertyChanged("Selected");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Fuzzware.Fuzzsaw.FuzzingConfig.FuzzDataLibrary")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:Fuzzware.Fuzzsaw.FuzzingConfig.FuzzDataLibrary", IsNullable=false)]
    public partial class FuzzDataFile : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool selectedField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Selected {
            get {
                return this.selectedField;
            }
            set {
                this.selectedField = value;
                this.RaisePropertyChanged("Selected");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Fuzzware.Fuzzsaw.FuzzingConfig.FuzzDataLibrary")]
    [System.Xml.Serialization.XmlRootAttribute("FuzzDataSubSection", Namespace="urn:Fuzzware.Fuzzsaw.FuzzingConfig.FuzzDataLibrary", IsNullable=false)]
    public partial class FuzzDataSubSectionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] itemsField;
        
        private string nameField;
        
        private FuzzDataSubSectionTypeSelected selectedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FuzzData", typeof(FuzzData))]
        [System.Xml.Serialization.XmlElementAttribute("FuzzDataFile", typeof(FuzzDataFile))]
        [System.Xml.Serialization.XmlElementAttribute("FuzzDataRange", typeof(FuzzDataRange))]
        [System.Xml.Serialization.XmlElementAttribute("FuzzDataSubSection", typeof(FuzzDataSubSectionType))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public FuzzDataSubSectionTypeSelected Selected {
            get {
                return this.selectedField;
            }
            set {
                this.selectedField = value;
                this.RaisePropertyChanged("Selected");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Fuzzware.Fuzzsaw.FuzzingConfig.FuzzDataLibrary")]
    public enum FuzzDataSubSectionTypeSelected {
        
        /// <remarks/>
        All,
        
        /// <remarks/>
        Some,
        
        /// <remarks/>
        None,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Fuzzware.Fuzzsaw.FuzzingConfig.FuzzDataLibrary")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:Fuzzware.Fuzzsaw.FuzzingConfig.FuzzDataLibrary", IsNullable=false)]
    public partial class FuzzDataSection : FuzzDataSubSectionType {
        
        private FuzzDataSectionDataType dataTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public FuzzDataSectionDataType DataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
                this.RaisePropertyChanged("DataType");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Fuzzware.Fuzzsaw.FuzzingConfig.FuzzDataLibrary")]
    public enum FuzzDataSectionDataType {
        
        /// <remarks/>
        String,
        
        /// <remarks/>
        Integer,
        
        /// <remarks/>
        Decimal,
        
        /// <remarks/>
        Binary,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Fuzzware.Fuzzsaw.FuzzingConfig.FuzzDataLibrary")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:Fuzzware.Fuzzsaw.FuzzingConfig.FuzzDataLibrary", IsNullable=false)]
    public partial class FuzzDataLibrary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FuzzDataSection[] fuzzDataSectionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FuzzDataSection")]
        public FuzzDataSection[] FuzzDataSection {
            get {
                return this.fuzzDataSectionField;
            }
            set {
                this.fuzzDataSectionField = value;
                this.RaisePropertyChanged("FuzzDataSection");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
