using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Reflection;
using System.Linq;
using System.Text;
using System.Windows;
using Fuzzware.Fuzzsaw.Common;
using Fuzzware.Schemer.AutoGenerated;

namespace Fuzzware.Fuzzsaw.FuzzingConfig
{
    public class StringFuzzerView : BaseFuzzerView
    {
        #region Bindable Objects Setup
        // String Length fuzzers data
        public static DependencyProperty ReplaceWithLongStringsFuzzDataProperty;
        public static DependencyProperty InsertLongStringsFuzzDataProperty;
        public static DependencyProperty InsertToLengthLongStringsFuzzDataProperty;
        // String value fuzzers data
        public static DependencyProperty ReplaceStringsFuzzDataProperty;
        public static DependencyProperty InsertStringsFuzzDataProperty;
        public static DependencyProperty EncodeStringsFuzzDataProperty;
        // Range data
        public static DependencyProperty InsertLongStringsRangeProperty;
        public static DependencyProperty InsertToLengthLongStringsRangeProperty;
        public static DependencyProperty InsertStringsRangeProperty;

        static StringFuzzerView()
        {
            ReplaceWithLongStringsFuzzDataProperty = DependencyProperty.Register("ReplaceWithLongStringsFuzzData", typeof(ObservableCollection<ObservableString>), typeof(StringFuzzerView),
                new FrameworkPropertyMetadata(new ObservableCollection<ObservableString>()));
            InsertLongStringsFuzzDataProperty = DependencyProperty.Register("InsertLongStringsFuzzData", typeof(ObservableCollection<ObservableString>), typeof(StringFuzzerView),
                new FrameworkPropertyMetadata(new ObservableCollection<ObservableString>()));
            InsertToLengthLongStringsFuzzDataProperty = DependencyProperty.Register("InsertToLengthLongStringsFuzzData", typeof(ObservableCollection<ObservableString>), typeof(StringFuzzerView),
                new FrameworkPropertyMetadata(new ObservableCollection<ObservableString>()));
            ReplaceStringsFuzzDataProperty = DependencyProperty.Register("ReplaceStringsFuzzData", typeof(ObservableCollection<ObservableString>), typeof(StringFuzzerView),
                new FrameworkPropertyMetadata(new ObservableCollection<ObservableString>()));
            InsertStringsFuzzDataProperty = DependencyProperty.Register("InsertStringsFuzzData", typeof(ObservableCollection<ObservableString>), typeof(StringFuzzerView),
                new FrameworkPropertyMetadata(new ObservableCollection<ObservableString>()));
            EncodeStringsFuzzDataProperty = DependencyProperty.Register("EncodeStringsFuzzData", typeof(ObservableCollection<ObservableString>), typeof(StringFuzzerView),
                new FrameworkPropertyMetadata(new ObservableCollection<ObservableString>()));
            InsertLongStringsRangeProperty = DependencyProperty.Register("InsertLongStringsRange", typeof(RangeDataView), typeof(StringFuzzerView));
            InsertToLengthLongStringsRangeProperty = DependencyProperty.Register("InsertToLengthLongStringsRange", typeof(RangeDataView), typeof(StringFuzzerView));
            InsertStringsRangeProperty = DependencyProperty.Register("InsertStringsRange", typeof(RangeDataView), typeof(StringFuzzerView));
        }

        public ObservableCollection<ObservableString> ReplaceWithLongStringsFuzzData
        {
            get { return (ObservableCollection<ObservableString>)GetValue(ReplaceWithLongStringsFuzzDataProperty); }
            set { SetValue(ReplaceWithLongStringsFuzzDataProperty, value); }
        }

        public ObservableCollection<ObservableString> InsertLongStringsFuzzData
        {
            get { return (ObservableCollection<ObservableString>)GetValue(InsertLongStringsFuzzDataProperty); }
            set { SetValue(InsertLongStringsFuzzDataProperty, value); }
        }

        public ObservableCollection<ObservableString> InsertToLengthLongStringsFuzzData
        {
            get { return (ObservableCollection<ObservableString>)GetValue(InsertToLengthLongStringsFuzzDataProperty); }
            set { SetValue(InsertToLengthLongStringsFuzzDataProperty, value); }
        }

        public ObservableCollection<ObservableString> ReplaceStringsFuzzData
        {
            get { return (ObservableCollection<ObservableString>)GetValue(ReplaceStringsFuzzDataProperty); }
            set { SetValue(ReplaceStringsFuzzDataProperty, value); }
        }

        public ObservableCollection<ObservableString> InsertStringsFuzzData
        {
            get { return (ObservableCollection<ObservableString>)GetValue(InsertStringsFuzzDataProperty); }
            set { SetValue(InsertStringsFuzzDataProperty, value); }
        }

        public ObservableCollection<ObservableString> EncodeStringsFuzzData
        {
            get { return (ObservableCollection<ObservableString>)GetValue(EncodeStringsFuzzDataProperty); }
            set { SetValue(EncodeStringsFuzzDataProperty, value); }
        }

        public RangeDataView InsertLongStringsRange
        {
            get { return (RangeDataView)GetValue(InsertLongStringsRangeProperty); }
            set { SetValue(InsertLongStringsRangeProperty, value); }
        }

        public RangeDataView InsertToLengthLongStringsRange
        {
            get { return (RangeDataView)GetValue(InsertToLengthLongStringsRangeProperty); }
            set { SetValue(InsertToLengthLongStringsRangeProperty, value); }
        }

        public RangeDataView InsertStringsRange
        {
            get { return (RangeDataView)GetValue(InsertStringsRangeProperty); }
            set { SetValue(InsertStringsRangeProperty, value); }
        }
        #endregion

        private void PopulateFuzzData(SimpleTypeFuzzerConfig oSTFC, StringLengthFuzzersType oSLFT, StringValueFuzzersType oSVFT)
        {
            // Always call populate so we add the final value to the collections that allows us to add new values
            PopulateLengthFuzzData((null != oSLFT) ? oSLFT.StringLength : null, oSTFC.StringLengthFuzzer, ReplaceWithLongStringsFuzzData, GetRefName(ReplaceWithLongStringsFuzzDataProperty));
            PopulateLengthFuzzData((null != oSLFT) ? oSLFT.InsertStringLength : null, oSTFC.StringLengthFuzzer, InsertLongStringsFuzzData, GetRefName(InsertLongStringsFuzzDataProperty));
            PopulateLengthFuzzData((null != oSLFT) ? oSLFT.InsertTotalStringLength : null, oSTFC.StringLengthFuzzer, InsertToLengthLongStringsFuzzData, GetRefName(InsertToLengthLongStringsFuzzDataProperty));

            PopulateValueFuzzData((null != oSVFT) ? oSVFT.ReplaceString : null, oSTFC.StringValueFuzzer, ReplaceStringsFuzzData, GetRefName(ReplaceStringsFuzzDataProperty));
            PopulateValueFuzzData((null != oSVFT) ? oSVFT.InsertString : null, oSTFC.StringValueFuzzer, InsertStringsFuzzData, GetRefName(InsertStringsFuzzDataProperty));
            PopulateValueFuzzData((null != oSVFT) ? oSVFT.EncodeString : null, oSTFC.StringValueFuzzer, EncodeStringsFuzzData, GetRefName(EncodeStringsFuzzDataProperty));

            PopulateRangeData((null != oSLFT) ? oSLFT.InsertStringLength : null, (null != oSTFC.StringLengthFuzzer.LengthRange) ? oSTFC.StringLengthFuzzer.LengthRange : null, InsertLongStringsRange, GetRefName(InsertLongStringsRangeProperty));
            PopulateRangeData((null != oSLFT) ? oSLFT.InsertTotalStringLength : null, (null != oSTFC.StringLengthFuzzer.LengthRange) ? oSTFC.StringLengthFuzzer.LengthRange : null, InsertToLengthLongStringsRange, GetRefName(InsertToLengthLongStringsRangeProperty));
            PopulateRangeData((null != oSVFT) ? oSVFT.InsertString : null, (null != oSTFC.StringValueFuzzer.StringRange) ? oSTFC.StringValueFuzzer.StringRange : null, InsertStringsRange, GetRefName(InsertStringsRangeProperty));
        }

        /// <summary>
        /// The constructor for the default string fuzzer
        /// </summary>
        public StringFuzzerView(SimpleTypeFuzzerConfig oSTFC, StringLengthFuzzersType oSLFT, StringValueFuzzersType oSVFT)
        {
            InitProperties();
            m_bIsDefault = true;
            IsConfigEnabled = true;

            // For the default fuzzer, if there are no fuzzers configured, then disable config
            if ((null != oSLFT) && (null != oSVFT) &&
                (null == oSLFT.StringLength) &&
                (null == oSLFT.InsertStringLength) &&
                (null == oSLFT.InsertTotalStringLength) &&
                (null == oSVFT.ReplaceString) &&
                (null == oSVFT.InsertString) &&
                (null == oSVFT.EncodeString))
            {
                IsConfigEnabled = false;
            }

            PopulateFuzzData(oSTFC, oSLFT, oSVFT);
        }

        /// <summary>
        /// The constructor for the custom string fuzzer
        /// </summary>
        public StringFuzzerView(SimpleTypeFuzzerConfig oSTFC, StringLengthFuzzerCustomFuzzer oSLFCF, StringValueFuzzerCustomFuzzer oSVFCF)
        {
            InitProperties();
            // IsConfigEnabled is always true for custom fuzzers
            IsConfigEnabled = true;

            PopulateFuzzData(oSTFC, oSLFCF as StringLengthFuzzersType, oSVFCF as StringValueFuzzersType);

            // Get the custom node name and namespace
            if (null != oSLFCF)
            {
                CustomNodeNamespace = new ObservableString(oSLFCF.NodeNamespace);
                CustomNodeName = new ObservableString(oSLFCF.NodeName);
            }
            //else if ((null != CustomNodeName) && String.IsNullOrEmpty(CustomNodeName.Value) &&
            //    (null != CustomNodeNamespace) && String.IsNullOrEmpty(CustomNodeNamespace.Value) &&
            else if(null != oSVFCF)
            {
                CustomNodeNamespace = new ObservableString(oSVFCF.NodeNamespace);
                CustomNodeName = new ObservableString(oSVFCF.NodeName);
            }
        }

        /// <summary>
        /// I shouldn't need to do this, but when I don't I get weird behaviour, the properties contain the values
        /// of the last StringFuzzerConfig I populated.
        /// </summary>
        private void InitProperties()
        {
            ReplaceWithLongStringsFuzzData = new ObservableCollection<ObservableString>();
            InsertLongStringsFuzzData = new ObservableCollection<ObservableString>();
            InsertToLengthLongStringsFuzzData = new ObservableCollection<ObservableString>();
            ReplaceStringsFuzzData = new ObservableCollection<ObservableString>();
            InsertStringsFuzzData = new ObservableCollection<ObservableString>();
            EncodeStringsFuzzData = new ObservableCollection<ObservableString>();

            InsertLongStringsRange = new RangeDataView();
            InsertToLengthLongStringsRange = new RangeDataView();
            InsertStringsRange = new RangeDataView();
        }

        private void PopulateLengthFuzzData(ValueFuzzerType oFuzzerType, StringLengthFuzzer oSLF, ObservableCollection<ObservableString> BindableData, String DefaultRefName)
        {
            String ValueGroupRef = null;
            if ((null != oFuzzerType) && (null != oSLF))
            {
                // If the ValueFuzzerType exists
                ValueGroupRef = oFuzzerType.ValueGroupRef;
            }
            else if (m_bIsDefault && !IsConfigEnabled && (null != oSLF))
            {
                // If IsConfigEnabled = false, then this is the default fuzzer, and it is disabled
                ValueGroupRef = DefaultRefName;
            }

            if(!String.IsNullOrEmpty(ValueGroupRef))
            {
                StringLengthFuzzerLengthGroup oSLFLG = FindStringLengthGroup(ValueGroupRef, oSLF.LengthGroup);
                if (null != oSLFLG)
                    CopyFuzzData(oSLFLG.StringLength, BindableData);
            }
            // Always make sure the last item is the option to add a new value
            BindableData.Add(new ObservableString(ADD_A_VALUE));
        }

        private void PopulateValueFuzzData(ValueFuzzerType oFuzzerType, StringValueFuzzer oSVF, ObservableCollection<ObservableString> BindableData, String DefaultRefName)
        {
            String ValueGroupRef = null;
            if ((null != oFuzzerType) && (null != oSVF))
            {
                ValueGroupRef = oFuzzerType.ValueGroupRef;
            }
            else if (m_bIsDefault && !IsConfigEnabled && (null != oSVF))
            {
                // If IsConfigEnabled = false, then this is the default fuzzer, and it is disabled
                ValueGroupRef = DefaultRefName;
            }
            if (!String.IsNullOrEmpty(ValueGroupRef))
            {
                StringValueFuzzerStringGroup oSVFSG = FindStringValueGroup(ValueGroupRef, oSVF.StringGroup);
                if (null != oSVFSG)
                    CopyFuzzData(oSVFSG.StringValue, BindableData);
            }
            // Always make sure the last item is the option to add a new value
            BindableData.Add(new ObservableString(ADD_A_VALUE));
        }

        /// <summary>
        /// Find the string length fuzz data
        /// </summary>
        private StringLengthFuzzerLengthGroup FindStringLengthGroup(String Name, StringLengthFuzzerLengthGroup[] oSLFLG)
        {
            if (null != oSLFLG)
            {
                for (int i = 0; i < oSLFLG.Length; i++)
                {
                    if (oSLFLG[i].ID.Equals(Name))
                        return oSLFLG[i];
                }
            }
            return null;
        }

        /// <summary>
        /// Find the string value fuzz data
        /// </summary>
        private StringValueFuzzerStringGroup FindStringValueGroup(String Name, StringValueFuzzerStringGroup[] oSVFSG)
        {
            if (null != oSVFSG)
            {
                for (int i = 0; i < oSVFSG.Length; i++)
                {
                    if (oSVFSG[i].ID.Equals(Name))
                        return oSVFSG[i];
                }
            }
            return null;
        }

        /// <summary>
        /// The save the current String types view to its original data source
        /// </summary>
        public void SaveStringTypeConfig(SimpleTypeFuzzerConfig oSTFC)
        {
            SaveStringLengthTypeConfig(oSTFC);
            SaveStringValueTypeConfig(oSTFC);
        }

        /// <summary>
        /// The save the current String Length types view to its original data source
        /// </summary>
        protected void SaveStringLengthTypeConfig(SimpleTypeFuzzerConfig oSTFC)
        {
            if (null == oSTFC.StringLengthFuzzer)
                oSTFC.StringLengthFuzzer = new StringLengthFuzzer();

            // Save the default string fuzzers
            StringLengthFuzzer oSLF = oSTFC.StringLengthFuzzer;
            // Create the string length fuzzers
            StringLengthFuzzersType oSLFT = CreateStringLengthFuzzersType();
            oSLFT.StringLength = CreateValueFuzzerType(ReplaceWithLongStringsFuzzData, GetRefName(ReplaceWithLongStringsFuzzDataProperty), null, null);
            oSLFT.InsertStringLength = CreateValueFuzzerType(InsertLongStringsFuzzData, GetRefName(InsertLongStringsFuzzDataProperty), InsertLongStringsRange, GetRefName(InsertLongStringsRangeProperty));
            oSLFT.InsertTotalStringLength = CreateValueFuzzerType(InsertToLengthLongStringsFuzzData, GetRefName(InsertToLengthLongStringsFuzzDataProperty), InsertToLengthLongStringsRange, GetRefName(InsertToLengthLongStringsRangeProperty));
            // Add the fuzzers as either the default or a custom
            if (m_bIsDefault)
                oSLF.DefaultFuzzers = oSLFT;
            else
            {
                List<StringLengthFuzzerCustomFuzzer> oSLFCFList = new List<StringLengthFuzzerCustomFuzzer>(oSLF.CustomFuzzer);
                oSLFCFList.Add(oSLFT as StringLengthFuzzerCustomFuzzer);
                oSLF.CustomFuzzer = oSLFCFList.ToArray();
            }
            // Create the string length fuzzer value groups
            List<StringLengthFuzzerLengthGroup> oStringLengthGroups = new List<StringLengthFuzzerLengthGroup>(oSLF.LengthGroup);
            StringLengthFuzzerLengthGroup oSLFLG = new StringLengthFuzzerLengthGroup();
            // Add the ValueGroups, always add the default ones, even if no fuzzers were being used
            if ((null != oSLFT.StringLength) || m_bIsDefault)
            {
                oSLFLG.ID = m_bIsDefault ? GetRefName(ReplaceWithLongStringsFuzzDataProperty) : oSLFT.StringLength.ValueGroupRef;
                oSLFLG.StringLength = GetUIntArray(ReplaceWithLongStringsFuzzData);
                oStringLengthGroups.Add(oSLFLG);
            }
            if ((null != oSLFT.InsertStringLength) || m_bIsDefault)
            {
                oSLFLG = new StringLengthFuzzerLengthGroup();
                oSLFLG.ID = m_bIsDefault ? GetRefName(InsertLongStringsFuzzDataProperty) : oSLFT.InsertStringLength.ValueGroupRef;
                oSLFLG.StringLength = GetUIntArray(InsertLongStringsFuzzData);
                oStringLengthGroups.Add(oSLFLG);
            }
            if ((null != oSLFT.InsertTotalStringLength) || m_bIsDefault)
            {
                oSLFLG = new StringLengthFuzzerLengthGroup();
                oSLFLG.ID = m_bIsDefault ? GetRefName(InsertToLengthLongStringsFuzzDataProperty) : oSLFT.InsertTotalStringLength.ValueGroupRef;
                oSLFLG.StringLength = GetUIntArray(InsertToLengthLongStringsFuzzData);
                oStringLengthGroups.Add(oSLFLG);
            }
            oSLF.LengthGroup = oStringLengthGroups.ToArray();

            // Create the ValueRanges
            List<ValueRange> oValueRangeList = new List<ValueRange>(oSLF.LengthRange);
            AddValueRange(oValueRangeList, oSLFT.InsertStringLength, InsertLongStringsRange, GetRefName(InsertLongStringsRangeProperty));
            AddValueRange(oValueRangeList, oSLFT.InsertTotalStringLength, InsertToLengthLongStringsRange, GetRefName(InsertToLengthLongStringsRangeProperty));
            oSLF.LengthRange = oValueRangeList.ToArray();
        }

        /// <summary>
        /// If default return a StringLengthFuzzersType, if not default return StringLengthFuzzerCustomFuzzer and populate
        /// node name and namespace.  If not default and no name and namespace, return null.
        /// </summary>
        protected StringLengthFuzzersType CreateStringLengthFuzzersType()
        {
            if (m_bIsDefault)
                return new StringLengthFuzzersType();
            else
            {
                if (String.IsNullOrEmpty(CustomNodeName.Value) && String.IsNullOrEmpty(CustomNodeNamespace.Value))
                    return null;

                StringLengthFuzzerCustomFuzzer oSLFCF = new StringLengthFuzzerCustomFuzzer();
                oSLFCF.NodeName = CustomNodeName.Value;
                oSLFCF.NodeNamespace = CustomNodeNamespace.Value;
                return oSLFCF as StringLengthFuzzersType;
            }
        }

        /// <summary>
        /// The save the current String Value types view to its original data source
        /// </summary>
        protected void SaveStringValueTypeConfig(SimpleTypeFuzzerConfig oSTFC)
        {
            if (null == oSTFC.StringLengthFuzzer)
                oSTFC.StringLengthFuzzer = new StringLengthFuzzer();

            // Save the default string fuzzers
            StringValueFuzzer oSVF = oSTFC.StringValueFuzzer;
            // Create the string length fuzzers
            StringValueFuzzersType oSVFT = CreateStringValueFuzzersType();
            oSVFT.ReplaceString = CreateValueFuzzerType(ReplaceStringsFuzzData, GetRefName(ReplaceStringsFuzzDataProperty), null, null);
            oSVFT.InsertString = CreateValueFuzzerType(InsertStringsFuzzData, GetRefName(InsertStringsFuzzDataProperty), InsertStringsRange, GetRefName(InsertStringsRangeProperty));
            oSVFT.EncodeString = CreateValueFuzzerType(EncodeStringsFuzzData, GetRefName(EncodeStringsFuzzDataProperty), null, null);
            // Add the fuzzers as either the default or a custom
            if (m_bIsDefault)
                oSVF.DefaultFuzzers = oSVFT;
            else
            {
                List<StringValueFuzzerCustomFuzzer> oSLFCFList = new List<StringValueFuzzerCustomFuzzer>(oSVF.CustomFuzzer);
                oSLFCFList.Add(oSVFT as StringValueFuzzerCustomFuzzer);
                oSVF.CustomFuzzer = oSLFCFList.ToArray();
            }
            // Create the string value fuzzer value groups
            List<StringValueFuzzerStringGroup> oStringGroups = new List<StringValueFuzzerStringGroup>(oSVF.StringGroup);
            StringValueFuzzerStringGroup oSVFSG = new StringValueFuzzerStringGroup();
            // Add the ValueGroups, always add the default ones, even if no fuzzers were being used
            if ((null != oSVFT.ReplaceString) || m_bIsDefault)
            {
                oSVFSG.ID = m_bIsDefault ? GetRefName(ReplaceStringsFuzzDataProperty) : oSVFT.ReplaceString.ValueGroupRef;
                oSVFSG.StringValue = GetStringArray(ReplaceStringsFuzzData);
                oStringGroups.Add(oSVFSG);
            }
            if ((null != oSVFT.InsertString) || m_bIsDefault)
            {
                oSVFSG = new StringValueFuzzerStringGroup();
                oSVFSG.ID = m_bIsDefault ? GetRefName(InsertStringsFuzzDataProperty) : oSVFT.InsertString.ValueGroupRef;
                oSVFSG.StringValue = GetStringArray(InsertStringsFuzzData);
                oStringGroups.Add(oSVFSG);
            }
            if ((null != oSVFT.EncodeString) || m_bIsDefault)
            {
                oSVFSG = new StringValueFuzzerStringGroup();
                oSVFSG.ID = m_bIsDefault ? GetRefName(EncodeStringsFuzzDataProperty) : oSVFT.EncodeString.ValueGroupRef;
                oSVFSG.StringValue = GetStringArray(EncodeStringsFuzzData);
                oStringGroups.Add(oSVFSG);
            }
            oSVF.StringGroup = oStringGroups.ToArray();

            // Create the ValueRanges
            List<ValueRange> oValueRangeList = new List<ValueRange>(oSVF.StringRange);
            AddValueRange(oValueRangeList, oSVFT.InsertString, InsertStringsRange, GetRefName(InsertStringsRangeProperty));
            oSVF.StringRange = oValueRangeList.ToArray();
        }

        /// <summary>
        /// If default return a StringValueFuzzersType, if not default return StringValueFuzzerCustomFuzzer and populate
        /// node name and namespace.  If not default and no name and namespace, return null.
        /// </summary>
        protected StringValueFuzzersType CreateStringValueFuzzersType()
        {
            if (m_bIsDefault)
                return new StringValueFuzzersType();
            else
            {
                if (String.IsNullOrEmpty(CustomNodeName.Value) && String.IsNullOrEmpty(CustomNodeNamespace.Value))
                    return null;

                StringValueFuzzerCustomFuzzer oSLFCF = new StringValueFuzzerCustomFuzzer();
                oSLFCF.NodeName = CustomNodeName.Value;
                oSLFCF.NodeNamespace = CustomNodeNamespace.Value;
                return oSLFCF as StringValueFuzzersType;
            }
        }
    }
}
