using System;
using System.Collections.Generic;
using System.Text;
using Fuzzware.Common;
using Fuzzware.Common.XML;
using Fuzzware.Schemer.AutoGenerated;

namespace Fuzzware.Schemer.Fuzzers.BinaryFuzzing
{
    class AndBytes : BinaryFuzzerBase
    {
        public AndBytes(ConfigData oConfigData, PreCompData oPreCompData, ObjectDBEntry oSchemaElement)
            : base(oConfigData, oPreCompData, oSchemaElement)
        {
        }

        protected override void AssignValueFuzzers(ByteValueFuzzersType FuzzersType)
        {
            if (null != FuzzersType.AndBytes)
            {
                Add("AndBytes", AndBytesFn);
                FuzzingValues = GetByteGroup(FuzzersType.AndBytes.ValueGroupRef);
                BytesVR = GetValueRange(FuzzersType.AndBytes.ValueRangeRef, ValueConfig.ByteRange);
            }
        }

        /// <summary>
        /// Binary And bytes in the current byte value with values from the user configured list.  If there is an
        /// associated Value Range then only bytes in the specified position will be changed.  Otherwise all the
        /// bytes will be And'ed, starting with the first and incrementing by one.
        /// </summary>
        public bool AndBytesFn(int FuzzIndex, int NodeIndex)
        {
            return EditBytes(FuzzIndex, NodeIndex, FuzzingValues, BytesVR);
        }

        /// <summary>
        /// Binary And the current byte array  value with the byte array value from the user configured list
        /// </summary>
        /// <param name="StartIndex">Where to start operating on bytes in the current byte array</param>
        /// <param name="FuzzByteValues">The bytes to use</param>
        /// <param name="OutputBytes">The current byte array to be changed</param>
        protected override void BinaryEditFn(int StartIndex, byte[] FuzzByteValues, ref byte[] OutputBytes)
        {
            for (int i = 0; i < FuzzByteValues.Length; i++)
                OutputBytes[StartIndex + i] = (byte)(OutputBytes[StartIndex + i] & FuzzByteValues[i]);
        }
    }
}
