using System;
using System.Collections.Generic;
using System.Text;
using System.Reflection;
using Fuzzware.Common;
using Fuzzware.Evaluate;
using Fuzzware.Schemas.AutoGenerated;
using Fuzzware.Convert2XML;

namespace Fuzzware.Schemer.OutputHandlers
{
    public class OutputToExeHandler : OutputHandler
    {
        OutputToExe oOutputToExe;
        EvaluationMethod EvalFn;

        public override void Initialise(object Settings, InputHandler oInputHandler)
        {
            if (!(Settings is OutputToExe))
                Log.Write(MethodInfo.GetCurrentMethod(), "Expected Settings object of type 'outputToExe', got '" + Settings.GetType().ToString() + "'", Log.LogType.Error);

            oOutputToExe = Settings as OutputToExe;

            EvalFn = new EvaluationMethod();
            EvalFn.Item = oOutputToExe;
        }

        public override bool Output(System.IO.MemoryStream XMLMemoryStream, string StateDesc)
        {
            return EvaluationFunctions.OutputToExe(XMLMemoryStream, EvalFn, StateDesc);
        }
    }
}
