using System;
using System.Collections.Generic;
using System.Text;
using System.Reflection;
using Fuzzware.Common;
using Fuzzware.Evaluate;
using Fuzzware.Schemas.AutoGenerated;
using Fuzzware.Convert2XML;

namespace Fuzzware.Schemer.OutputHandlers
{
    public class OutputToFileHandler: OutputHandler
    {
        FileStore oOutputToFile;
        EvaluationMethod EvalFn;

        public override void Initialise(object Settings, InputHandler oInputHandler)
        {
            if (!(Settings is FileStore))
                Log.Write(MethodInfo.GetCurrentMethod(), "Expected Settings object of type 'OutputFile', got '" + Settings.GetType().ToString() + "'", Log.LogType.Error);

            oOutputToFile = Settings as FileStore;

            EvalFn = new EvaluationMethod();
            EvalFn.Item = oOutputToFile;
        }

        public override bool Output(System.IO.MemoryStream XMLMemoryStream, string StateDesc)
        {
            return EvaluationFunctions.OutputToFile(XMLMemoryStream, EvalFn, StateDesc);
        }
    }
}
