using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Fuzzware.Convert2XML;
using Fuzzware.Schemas.AutoGenerated;

namespace Fuzzware.Schemer.OutputHandlers
{
    public abstract class OutputHandler
    {
        public abstract void Initialise(object Settings, InputHandler oInputHandler);

        public abstract bool Output(MemoryStream XMLMemoryStream, String StateDesc);
    }
}
